http:
  host: "![Je3vy5ehh5dSGsG1V2Y1+Q==]"
  path: "![JZn5O2puPBh6toMCDdoJMvvUGCTtqBHblOstzNkRdY4=]"
  port: "![EI0ep67lOdI=]"

banknative:
  host: "![+szQGKs7bXvej0XhCr45hGCDC6UTvQTHe4Qn38gGTpv2FX+6fKsvWe5WFdiyVmzl]"
  path : "![Do9odAKExRV6wuUm9JU9qcBzAB2Oe/kM]"
  accountbalancepath: "![Puz9rIPiYIhExGPVvoR+H/ohRkYgM5qg]"
